### ISSUE TITLE
concat issue

### ISSUE THREAD

**Issue by blucap** [aaronpenne/get_noaa_ghcn_data#3]
The usual concat issue arose:  

```
/get_noaa_ghcn_data/get_dly.py:202: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version of pandas will change to not sort by default. 

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.
```
Just add 'sort=False' to line 202 of `get_dly.py`

`df_all = pd.concat(list_dfs, axis=1, sort=False)`

**Comment by aaronpenne** [comment]
Thank you @blucap, I'll have to fix this in other repos. Also, the [pandas team is doing away](https://www.dataschool.io/future-of-pandas/) with the `inplace` parameter so that will need to be updated in pretty much every file I have on here.

Issue fixed and closed.
